### PR TITLE
Change Date format for GraphQL response to return the same format as REST API do

### LINKED ISSUE #94: REST api returns ISO string but GraphQL returns epoch milliseconds
**Describe the bug**
For example property `CratedAt` in changelog reponse:
`"createdAt": "2025-11-20T08:20:58.174Z"` vs `"createdAt": "1763626837802"`

**To Reproduce**
Call `changelog` endpoint and `ChangelogByEvent` in GraphQL.

**Expected behavior**
Get the same data format for both APIs.

**Additional context**
Package graphql-scalars should help to fix it. It looks that by default, GraphQL turns JavaScript Date objects into timestamps. We will probably have to implement custom `Date` scalar.

### PR DESCRIPTION
**Pull request by lukaskett**
Add custom date scalar to make graphql return date as ISO 8601 string instead of unix timestamp in milliseconds to keep consistency between both rest and graphql. Changed for values:
- createdAt (changelog)
- updatedAt (Competitor)

fix #94

### CODE REVIEW

**Comment by lukaskett** [comment]
`dateScalar.js` is general and not specific only for `changelog`. The file should be placed higher in the file structure - in the same folder as `executableSchema.js`.

**Comment by lukaskett** [comment]
Current state
```json
{
  "data": {
    "event": {
      "date": "2025-11-02T00:00:00.000Z",
      "zeroTime": "2025-11-02T17:00:00.000Z",
      "createdAt": "2025-11-02T17:16:25.545Z",
      "updatedAt": "2025-11-02T17:16:25.545Z",
      "user": {
        "createdAt": "2025-11-02T17:12:20.505Z",
        "updatedAt": "2025-11-02T17:12:20.505Z"
      },
      "classes": [
        {
          "competitors": [
            {
              "updatedAt": "2025-11-27T21:30:06.037Z"
            }
          ]
        }
      ]
    }
  }
}
```

File: apps/server/src/graphql/competitor/schema.js [hunk 1]
```diff
@@ -48,7 +48,7 @@ export const typeDef = /* GraphQL */ `
     lateStart: Boolean!
     note: String
     externalId: String
-    updatedAt: String!
+    updatedAt: Date!
```
Comment (martinkrivda) [inline apps/server/src/graphql/competitor/schema.js]: DateTime

**Comment by martinkrivda** [comment]
@lukaskett, could you please test the changes and confirm that everything is now working correctly and meets your expectations?

**Comment by lukaskett** [comment]
> @lukaskett, could you please test the changes and confirm that everything is now working correctly and meets your expectations?

confirmed, it works as expected 👍 thanks,

**Review by martinkrivda — APPROVED** [review]
